import { useEffect, useRef, useState } from 'react'
import './App.css'
import './modules.css'
import { createMenuItem, createOrder, createReservation, getDashboard, getInventory, getMenu, getSession, login, logout, updateInventory, updateOrderStatus, type Dashboard, type InventoryItem, type MenuItem, type OrderLine, type RestaurantTable, type Role, type SessionUser } from './api'

type IconProps = { size?: number }
type IconComponent = (props: IconProps) => React.ReactNode
const makeIcon = (symbol: string): IconComponent => ({ size = 18 }) => <span className="local-icon" style={{ fontSize: size - 2 }}>{symbol}</span>
const Archive = makeIcon('▣'), ArrowUpRight = makeIcon('↗'), Bell = makeIcon('◌'), CalendarDays = makeIcon('▦')
const ChevronDown = makeIcon('⌄'), ChefHat = makeIcon('♨'), CircleDollarSign = makeIcon('€'), ClipboardList = makeIcon('☷')
const Clock3 = makeIcon('◷'), LayoutDashboard = makeIcon('▤'), Map = makeIcon('⌖'), MoreHorizontal = makeIcon('···')
const Package = makeIcon('□'), Plus = makeIcon('+'), Settings = makeIcon('⚙')
const Utensils = makeIcon('♧'), Users = makeIcon('♙'), WalletCards = makeIcon('▭')

type NavItem = { label: string; icon: IconComponent; badge?: string }
const navItems: NavItem[] = [
  { label: 'Vue d’ensemble', icon: LayoutDashboard }, { label: 'Menu & plats', icon: Utensils }, { label: 'Réservations', icon: CalendarDays, badge: '12' },
  { label: 'Prise de commande', icon: ClipboardList }, { label: 'Plan de salle', icon: Map },
  { label: 'Cuisine', icon: ChefHat, badge: '8' }, { label: 'Caisse & paiements', icon: WalletCards },
]
function App() {
  const [activeNav, setActiveNav] = useState('Vue d’ensemble')
  const [showAdd, setShowAdd] = useState(false)
  const [alertVisible, setAlertVisible] = useState(true)
  const [dashboard, setDashboard] = useState<Dashboard | null>(null)
  const [apiError, setApiError] = useState('')
  const [role, setRole] = useState<Role>('manager')
  const [sessionUser, setSessionUser] = useState<SessionUser | null>(null)
  const [sessionReady, setSessionReady] = useState(false)
  const [inventory, setInventory] = useState<InventoryItem[]>([])
  const [selectedTable, setSelectedTable] = useState('')
  const [mobileNavOpen, setMobileNavOpen] = useState(false)
  const [serverNotice, setServerNotice] = useState('')
  const [menu, setMenu] = useState<MenuItem[]>([])
  const previousOrderStatuses = useRef<Record<string, string>>({})

  useEffect(() => {
    const token = localStorage.getItem('restaurant-token')
    const restore = token ? getSession().then(({ user }) => user) : login('manager', '1234').then(({ token: freshToken, user }) => { localStorage.setItem('restaurant-token', freshToken); return user })
    restore.then((user) => { setSessionUser(user); setRole(user.role); setActiveNav(user.role === 'kitchen' ? 'Cuisine' : user.role === 'cashier' ? 'Caisse & paiements' : user.role === 'server' ? 'Prise de commande' : 'Vue d’ensemble'); return Promise.all([getDashboard(), getInventory(), getMenu()]) }).then(([data, stock, dishes]) => { previousOrderStatuses.current = Object.fromEntries(data.orders.map((order) => [order.id, order.status])); setDashboard(data); setInventory(stock); setMenu(dishes) }).catch(() => { localStorage.removeItem('restaurant-token'); setApiError('API indisponible : lancez npm run api') }).finally(() => setSessionReady(true))
  }, [])
  useEffect(() => {
    if (!sessionUser) return
    const poll = window.setInterval(() => { getDashboard().then((next) => { const ready = next.orders.find((order) => order.status === 'ready' && previousOrderStatuses.current[order.id] !== 'ready'); if (ready && (role === 'server' || role === 'manager')) setServerNotice(`La commande #${ready.id} de la table ${ready.table} est prête.`); previousOrderStatuses.current = Object.fromEntries(next.orders.map((order) => [order.id, order.status])); setDashboard(next) }).catch(() => undefined) }, 8000)
    return () => window.clearInterval(poll)
  }, [sessionUser, role])
  const tables = dashboard?.tables || []
  const reservations = dashboard?.reservations || []
  const tableZones = [...new Set(tables.map((table) => table.zone))]
  const currentStats = dashboard?.stats

  const handleReservation = async (data: { name: string; time: string; people: number }) => {
    try {
      const reservation = await createReservation(data)
      setDashboard((current) => current ? { ...current, reservations: [...current.reservations, reservation] } : current)
      setShowAdd(false)
    } catch { setApiError('Impossible d’enregistrer la réservation. Vérifiez que l’API est démarrée.') }
  }
  const handleOrder = async (items: OrderLine[], amount: number, note: string) => {
    if (!selectedTable) return
    try { const order = await createOrder({ table: selectedTable, items, amount, note }); setDashboard((current) => current ? { ...current, orders: [order, ...current.orders] } : current); setServerNotice(`Commande #${order.id} envoyée en cuisine.`) } catch { setApiError('Impossible d’envoyer la commande. Vérifiez le rôle du serveur.') }
  }
  const handleOrderStatus = async (id: string, status: string) => {
    try { const updated = await updateOrderStatus(id, status); setDashboard((current) => current ? { ...current, orders: current.orders.map((order) => order.id === id ? updated : order) } : current) } catch { setApiError('Impossible de modifier le statut de la commande.') }
  }
  const handleStock = async (id: string, quantity: number) => {
    try { const updated = await updateInventory(id, quantity); setInventory((current) => current.map((item) => item.id === id ? updated : item)) } catch { setApiError('Impossible de mettre à jour le stock.') }
  }
  const handleMenuItem = async (item: { name: string; price: number; image: string }) => { try { const dish = await createMenuItem(item); setMenu((current) => [...current, dish]) } catch { setApiError('Impossible d’ajouter ce plat au menu.') } }
  const switchRole = async (nextRole: Role) => {
    const pins: Record<Role, string> = { manager: '1234', server: '2222', kitchen: '3333', cashier: '4444' }
    try { const session = await login(nextRole, pins[nextRole]); localStorage.setItem('restaurant-token', session.token); setSessionUser(session.user); setRole(nextRole); setActiveNav(nextRole === 'kitchen' ? 'Cuisine' : nextRole === 'cashier' ? 'Caisse & paiements' : nextRole === 'server' ? 'Prise de commande' : 'Vue d’ensemble') } catch { setApiError('Connexion impossible pour ce rôle') }
  }
  const handleLogout = async () => { try { await logout() } finally { localStorage.removeItem('restaurant-token'); setSessionUser(null); setDashboard(null) } }

  const renderView = () => {
    if (activeNav === 'Vue d’ensemble') return <DashboardView dashboard={dashboard} tables={tables} tableZones={tableZones} reservations={reservations} onNavigate={setActiveNav} onTableSelect={(id) => { setSelectedTable(id); setActiveNav('Prise de commande') }} />
    if (activeNav === 'Plan de salle') return <ModuleView title="Plan de salle" description="Visualisez l’occupation et attribuez les tables." icon="⌖"><FloorPlan tables={tables} tableZones={tableZones} onSelect={(id) => { setSelectedTable(id); setActiveNav('Prise de commande') }} /></ModuleView>
    if (activeNav === 'Réservations') return <ModuleView title="Réservations" description="Gérez les arrivées et les couverts du service." icon="▦"><ReservationModule reservations={reservations} onCreate={() => setShowAdd(true)} /></ModuleView>
    if (activeNav === 'Cuisine') return <ModuleView title="Cuisine" description="Suivez les commandes envoyées au passe." icon="♨"><KitchenModule orders={dashboard?.orders || []} onStatus={handleOrderStatus} /></ModuleView>
    if (activeNav === 'Caisse & paiements') return <ModuleView title="Caisse & paiements" description="Contrôlez les additions et les règlements du service." icon="€"><CashierModule orders={dashboard?.orders || []} onPay={handleOrderStatus} /></ModuleView>
    if (activeNav === 'Prise de commande') return <ModuleView title="Prise de commande" description={selectedTable ? `Table ${selectedTable} sélectionnée` : 'Choisissez une table avant de commander.'} icon="☷"><OrderModule menu={menu} selectedTable={selectedTable} onNavigate={setActiveNav} onCreate={handleOrder} /></ModuleView>
    if (activeNav === 'Approvisionnement') return <ModuleView title="Approvisionnement" description="Surveillez les seuils et mettez à jour les quantités." icon="□"><InventoryModule items={inventory} onUpdate={handleStock} /></ModuleView>
    if (activeNav === 'Finances') return <ModuleView title="Finances" description="Suivez les encaissements et le chiffre d’affaires du service." icon="€"><FinanceModule orders={dashboard?.orders || []} /></ModuleView>
      if (activeNav === 'Menu & plats') return <ModuleView title="Menu & plats" description="Créez vos plats, leurs prix et leurs photos." icon="♧"><MenuModule items={menu} onCreate={handleMenuItem} /></ModuleView>
      if (!sessionUser) return <LoginScreen onLogin={(user, token) => { localStorage.setItem('restaurant-token', token); setSessionUser(user); setRole(user.role); setActiveNav(user.role === 'kitchen' ? 'Cuisine' : user.role === 'cashier' ? 'Caisse & paiements' : user.role === 'server' ? 'Prise de commande' : 'Vue d’ensemble'); setSessionReady(true); Promise.all([getDashboard(), getInventory(), getMenu()]).then(([data, stock, dishes]) => { previousOrderStatuses.current = Object.fromEntries(data.orders.map((order) => [order.id, order.status])); setDashboard(data); setInventory(stock); setMenu(dishes) }).catch(() => setApiError('Impossible de charger les données')) }} />
    return <ModuleView title="Paramètres" description="Contrôlez la session et les règles de votre établissement." icon="⚙"><SettingsModule user={sessionUser} onLogout={handleLogout} /></ModuleView>
  }
  if (!sessionReady) return <div className="session-loading">Vérification de la session...</div>
  if (!sessionUser) return <LoginScreen onLogin={(user, token) => { localStorage.setItem('restaurant-token', token); setSessionUser(user); setRole(user.role); setActiveNav(user.role === 'kitchen' ? 'Cuisine' : user.role === 'cashier' ? 'Caisse & paiements' : user.role === 'server' ? 'Prise de commande' : 'Vue d’ensemble'); setSessionReady(true); Promise.all([getDashboard(), getInventory()]).then(([data, stock]) => { setDashboard(data); setInventory(stock) }).catch(() => setApiError('Impossible de charger les données')) }} />
  return <div className="app-shell">
    <aside className={`sidebar ${mobileNavOpen ? 'mobile-open' : ''}`}>
      <div className="brand"><span className="brand-mark"><Utensils size={18} /></span><span>Service<span className="brand-accent">Pilot</span></span></div>
      <div className="workspace-switcher"><span className="avatar">LM</span><span><strong>Le Mijoté</strong><small>Restaurant · Paris 11e</small></span><ChevronDown size={15} /></div>
      <p className="nav-caption">PILOTAGE</p>
      <nav>{navItems.filter(({ label }) => role === 'manager' || (role === 'server' && ['Prise de commande', 'Plan de salle', 'Réservations'].includes(label)) || (role === 'kitchen' && label === 'Cuisine') || (role === 'cashier' && label === 'Caisse & paiements')).map(({ label, icon: Icon, badge }) => <button key={label} className={`nav-item ${activeNav === label ? 'active' : ''}`} onClick={() => { setActiveNav(label); setMobileNavOpen(false) }}><Icon size={18} /><span>{label}</span>{badge && <em>{badge}</em>}</button>)}</nav>
      <p className="nav-caption bottom-caption">ADMINISTRATION</p>
      {role === 'manager' && <><button className="nav-item" onClick={() => { setActiveNav('Approvisionnement'); setMobileNavOpen(false) }}><Package size={18} /><span>Approvisionnement</span></button><button className="nav-item" onClick={() => { setActiveNav('Finances'); setMobileNavOpen(false) }}><CircleDollarSign size={18} /><span>Finances</span></button><button className="nav-item" onClick={() => { setActiveNav('Paramètres'); setMobileNavOpen(false) }}><Settings size={18} /><span>Paramètres</span></button></>}
      <div className="sidebar-footer"><div className="support-icon"><Bell size={17} /></div><div><strong>Besoin d’aide ?</strong><small>Centre de support</small></div><ArrowUpRight size={15} /></div>
    </aside>
    <main className="main-content">
      <header className="topbar"><button className="mobile-menu-button" aria-label="Ouvrir le menu" onClick={() => setMobileNavOpen(!mobileNavOpen)}>☰</button><div className="breadcrumb"><button className="home-button" onClick={() => setActiveNav('Vue d’ensemble')}>Accueil</button><span className="dot">·</span><span>Bonjour {sessionUser.name}</span><span className="dot">·</span><span className="muted">Jeudi 24 septembre 2026</span></div><div className="top-actions"><button className="icon-button notification" aria-label="Notifications" onClick={() => { setAlertVisible(!alertVisible); setServerNotice('') }}><Bell size={19} />{(alertVisible || serverNotice) && <i />}</button><select className="role-select" aria-label="Rôle actif" value={role} onChange={(event) => switchRole(event.target.value as Role)}><option value="manager">Gérante</option><option value="server">Serveur</option><option value="kitchen">Cuisine</option><option value="cashier">Caissier</option></select><div className="profile"><span className="avatar profile-avatar">{sessionUser.name.slice(0, 2).toUpperCase()}</span><span><strong>{sessionUser.name}</strong><small>Session active</small></span><ChevronDown size={15} /></div><button className="logout-button" onClick={handleLogout}>Quitter</button></div></header>
      {apiError && <div className="api-error">{apiError}</div>}
      {serverNotice && <div className="server-notice"><Bell size={15} /><span>{serverNotice}</span><button onClick={() => setServerNotice('')} aria-label="Fermer">×</button></div>}
      {activeNav === 'Vue d’ensemble' && <div className="page-heading"><div><p className="eyebrow">JEUDI 24 SEPTEMBRE · SERVICE DU SOIR</p><h1>Vue d’ensemble</h1><p className="subtitle">Voici ce qui se passe dans votre restaurant aujourd’hui.</p></div><button className="primary-button" onClick={() => setShowAdd(true)}><Plus size={18} /> Nouvelle réservation</button></div>}
      {activeNav === 'Vue d’ensemble' && alertVisible && <div className="alert-banner"><div className="alert-symbol"><Archive size={18} /></div><div><strong>Stock à surveiller</strong><span>3 produits passent sous le seuil minimum cette semaine.</span></div><button onClick={() => setAlertVisible(false)} aria-label="Fermer">×</button></div>}
      {activeNav === 'Vue d’ensemble' && <section className="stats-grid"><StatCard icon={<CalendarDays size={19} />} label="Réservations du jour" value={String(currentStats?.reservations || 24)} note="+4 vs. jeudi dernier" trend="up" /><StatCard icon={<Users size={19} />} label="Couverts prévus" value={String(currentStats?.covers || 86)} note="72% de la capacité" trend="neutral" /><StatCard icon={<CircleDollarSign size={19} />} label="Chiffre d’affaires" value={`${(currentStats?.revenue || 2840).toLocaleString('fr-FR')} €`} note="+12,4% vs. hier" trend="up" /><StatCard icon={<Clock3 size={19} />} label="Temps moyen en salle" value={currentStats?.averageDuration || '1h42'} note="-8 min vs. moyenne" trend="up" /></section>}
      {renderView()}
    </main>
    {showAdd && <ReservationModal onClose={() => setShowAdd(false)} onSubmit={handleReservation} />}
  </div>
}
function StatCard({ icon, label, value, note, trend }: { icon: React.ReactNode; label: string; value: string; note: string; trend: 'up' | 'neutral' }) { return <article className="stat-card"><div className="stat-icon">{icon}</div><span className="stat-label">{label}</span><strong className="stat-value">{value}</strong><span className={`stat-note ${trend}`}>{note}</span></article> }
function Reservation({ time, name, detail, status }: { time: string; name: string; detail: string; status: string }) { return <div className="reservation"><time>{time}</time><div className="reservation-info"><strong>{name}</strong><span>{detail}</span></div><em>{status}</em></div> }
function Activity({ icon, color, title, detail, trailing }: { icon: React.ReactNode; color: string; title: string; detail: string; trailing: string }) { return <div className="activity-row"><span className={`activity-icon ${color}`}>{icon}</span><div><strong>{title}</strong><small>{detail}</small></div><span className={color === 'green' ? 'activity-tag' : 'activity-price'}>{trailing}</span></div> }
function DashboardView({ dashboard, tables, tableZones, reservations, onNavigate, onTableSelect }: { dashboard: Dashboard | null; tables: RestaurantTable[]; tableZones: string[]; reservations: Dashboard['reservations']; onNavigate: (view: string) => void; onTableSelect: (id: string) => void }) { return <><div className="content-grid"><section className="panel floor-panel"><div className="panel-heading"><div><h2>Plan de salle</h2><p>État des tables en temps réel</p></div><button className="text-button" onClick={() => onNavigate('Plan de salle')}>Voir le plan <ArrowUpRight size={15} /></button></div><FloorPlan tables={tables} tableZones={tableZones} onSelect={onTableSelect} /></section><section className="panel service-panel"><div className="panel-heading"><div><h2>Prochaines réservations</h2><p>Les arrivées des 90 prochaines minutes</p></div><button className="more-button" aria-label="Plus d’options"><MoreHorizontal size={19} /></button></div><div className="reservation-list">{reservations.slice(0, 3).map((reservation, index) => <Reservation key={reservation.id} time={reservation.time} name={reservation.name} detail={`${reservation.people} personnes · Table ${reservation.table}`} status={`Dans ${12 + index * 15} min`} />)}</div><button className="bottom-link" onClick={() => onNavigate('Réservations')}>Toutes les réservations <ArrowUpRight size={15} /></button></section></div><section className="panel activity-panel"><div className="panel-heading"><div><h2>Activité du service</h2><p>Suivi en direct de l’équipe</p></div><span className="live-status"><i /> En direct</span></div>{(dashboard?.orders || []).map((order) => <Activity key={order.id} icon={<ClipboardList size={17} />} color={order.status === 'paid' ? 'orange' : 'blue'} title={order.status === 'paid' ? `Addition #${order.id} encaissée` : `Commande #${order.id} envoyée en cuisine`} detail={`Table ${order.table} · ${order.items} articles`} trailing={`${order.amount.toFixed(2).replace('.', ',')} €`} />)}</section></> }
function FloorPlan({ tables, tableZones, onSelect }: { tables: RestaurantTable[]; tableZones: string[]; onSelect: (id: string) => void }) { return <><div className="floor-layout">{tableZones.map((zone) => <div className="zone" key={zone}><span className="zone-label">{zone}</span><div className="tables">{tables.filter((table) => table.zone === zone).map((table) => <button key={table.id} className={`table ${table.status}`} onClick={() => onSelect(table.id)}><span>{table.id}</span><small>{table.seats} pl.</small></button>)}</div></div>)}</div><div className="legend"><span><i className="legend-dot free-dot" />Libre</span><span><i className="legend-dot occupied-dot" />En service</span><span><i className="legend-dot reserved-dot" />Réservée</span></div></> }
function ModuleView({ title, description, icon, children }: { title: string; description: string; icon: string; children: React.ReactNode }) { return <><div className="page-heading module-heading"><div><p className="eyebrow">MODULE OPÉRATIONNEL</p><h1><span className="module-icon">{icon}</span>{title}</h1><p className="subtitle">{description}</p></div></div>{children}</> }
function ReservationModule({ reservations, onCreate }: { reservations: Dashboard['reservations']; onCreate: () => void }) { return <section className="panel module-list"><div className="module-list-heading"><strong>Réservations du service</strong><button className="text-button" onClick={onCreate}>+ Ajouter</button></div>{reservations.map((reservation) => <div className="module-row" key={reservation.id}><time>{reservation.time}</time><div><strong>{reservation.name}</strong><small>{reservation.people} personnes · Table {reservation.table}</small></div><span className="status-pill">Confirmée</span></div>)}</section> }
function KitchenModule({ orders, onStatus }: { orders: Dashboard['orders']; onStatus: (id: string, status: string) => void }) { const labels: Record<string, string> = { received: 'Reçue', preparing: 'En préparation', ready: 'Prête' }; return <section className="panel module-list"><div className="module-list-heading"><strong>Commandes à préparer</strong><span className="live-status"><i /> En direct</span></div>{orders.filter((order) => order.status !== 'paid').map((order) => <div className="module-row kitchen-row" key={order.id}><span className="order-number">#{order.id}</span><div><strong>Table {order.table}</strong><small>{order.items} articles · {order.note || 'Aucune remarque'}</small><span className="order-lines">{order.lines?.map((line) => `${line.quantity}× ${line.name}`).join(' · ')}</span></div><span className={`status-pill ${order.status === 'ready' ? '' : 'orange-pill'}`}>{labels[order.status]}</span>{order.status === 'received' && <button className="action-button" onClick={() => onStatus(order.id, 'preparing')}>Commencer</button>}{order.status === 'preparing' && <button className="action-button" onClick={() => onStatus(order.id, 'ready')}>Prête</button>}</div>)}</section> }
function CashierModule({ orders, onPay }: { orders: Dashboard['orders']; onPay: (id: string, status: string) => void }) { return <section className="panel module-list"><div className="module-list-heading"><strong>Encaissements du service</strong><span>{orders.filter((order) => order.status === 'paid').length} payé(s)</span></div>{orders.map((order) => <div className="module-row" key={order.id}><span className="order-number">#{order.id}</span><div><strong>Table {order.table}</strong><small>{order.items} articles · {order.amount.toFixed(2).replace('.', ',')} €</small></div>{order.status === 'paid' ? <span className="status-pill">Payée</span> : <button className="action-button" onClick={() => onPay(order.id, 'paid')}>Encaisser</button>}</div>)}</section> }
function OrderModule({ menu, selectedTable, onNavigate, onCreate }: { menu: MenuItem[]; selectedTable: string; onNavigate: (view: string) => void; onCreate: (items: OrderLine[], amount: number, note: string) => void }) { const [cart, setCart] = useState<OrderLine[]>([]); const [note, setNote] = useState(''); const addItem = (name: string, price: number) => setCart((current) => { const found = current.find((item) => item.name === name); return found ? current.map((item) => item.name === name ? { ...item, quantity: item.quantity + 1 } : item) : [...current, { name, price, quantity: 1 }] }); const changeQuantity = (name: string, quantity: number) => setCart((current) => quantity < 1 ? current.filter((item) => item.name !== name) : current.map((item) => item.name === name ? { ...item, quantity } : item)); const total = cart.reduce((sum, item) => sum + item.price * item.quantity, 0); return <section className="panel order-module"><div className="order-form"><span className="empty-icon">☷</span><h2>{selectedTable ? `Commande pour ${selectedTable}` : 'Choisissez une table pour commencer'}</h2>{selectedTable ? <><div className="menu-grid">{menu.filter((item) => item.active).map((item) => <button key={item.id} className="menu-item menu-card" onClick={() => addItem(item.name, item.price)}><img src={item.image} alt="" /><span><strong>{item.name}</strong><small>{item.price} € · Ajouter</small></span></button>)}</div><div className="order-summary"><strong>Votre commande</strong>{cart.length ? cart.map((item) => <div className="summary-row" key={item.name}><span>{item.name}</span><input type="number" min="1" value={item.quantity} aria-label={`Quantité ${item.name}`} onChange={(event) => changeQuantity(item.name, Number(event.target.value))} /><b>{(item.price * item.quantity).toFixed(2).replace('.', ',')} €</b></div>) : <p>Aucun article ajouté.</p>}<div className="summary-total"><span>Total</span><strong>{total.toFixed(2).replace('.', ',')} €</strong></div></div><label className="order-note">Remarque pour la cuisine<textarea value={note} onChange={(event) => setNote(event.target.value)} placeholder="Allergie, cuisson, sans accompagnement..." /></label><button className="primary-button" disabled={!cart.length} onClick={() => onCreate(cart, total, note)}>Envoyer en cuisine, rester au serveur <ArrowUpRight size={16} /></button></> : <><p>Le serveur peut sélectionner une table puis ajouter les articles.</p><button className="primary-button" onClick={() => onNavigate('Plan de salle')}>Choisir une table <ArrowUpRight size={16} /></button></>}</div></section> }
function InventoryModule({ items, onUpdate }: { items: InventoryItem[]; onUpdate: (id: string, quantity: number) => void }) { const [fileName, setFileName] = useState(''); return <section className="panel module-list"><div className="module-list-heading"><strong>État du stock</strong><span>{items.filter((item) => item.quantity <= item.minimum).length} alerte(s)</span></div><div className="stock-import"><label className="upload-button">Importer une facture PDF<input type="file" accept="application/pdf,image/*" capture="environment" onChange={(event) => setFileName(event.target.files?.[0]?.name || '')} /></label><span>{fileName || 'PDF ou photo de facture'}</span></div>{items.map((item) => <div className="module-row" key={item.id}><div><strong>{item.name}</strong><small>{item.supplier} · seuil {item.minimum} {item.unit}</small></div><input className="quantity-input" type="number" min="0" value={item.quantity} onChange={(event) => onUpdate(item.id, Number(event.target.value))} /><span className={`status-pill ${item.quantity <= item.minimum ? 'orange-pill' : ''}`}>{item.quantity <= item.minimum ? 'À commander' : 'OK'}</span></div>)}</section> }
function MenuModule({ items, onCreate }: { items: MenuItem[]; onCreate: (item: { name: string; price: number; image: string }) => void }) { const [name, setName] = useState(''); const [price, setPrice] = useState(''); const [image, setImage] = useState(''); return <section className="panel menu-admin"><div className="module-list-heading"><strong>Plats disponibles</strong><span>{items.length} plats</span></div><div className="menu-admin-grid">{items.map((item) => <article key={item.id}><img src={item.image} alt="" /><strong>{item.name}</strong><span>{item.price.toFixed(2).replace('.', ',')} €</span></article>)}</div><div className="add-dish"><strong>Créer un nouveau plat</strong><div className="dish-fields"><input placeholder="Nom du plat" value={name} onChange={(event) => setName(event.target.value)} /><input type="number" placeholder="Prix €" value={price} onChange={(event) => setPrice(event.target.value)} /><input placeholder="URL de la photo" value={image} onChange={(event) => setImage(event.target.value)} /><button className="action-button" disabled={!name || !price} onClick={() => { onCreate({ name, price: Number(price), image }); setName(''); setPrice(''); setImage('') }}>Ajouter au menu</button></div></div></section> }
function FinanceModule({ orders }: { orders: Dashboard['orders'] }) { const revenue = orders.filter((order) => order.status === 'paid').reduce((sum, order) => sum + order.amount, 0); const vat = revenue * 0.1; return <><section className="panel finance-grid"><article><span>CA encaissé</span><strong>{revenue.toFixed(2).replace('.', ',')} €</strong></article><article><span>TVA estimée (10%)</span><strong>{vat.toFixed(2).replace('.', ',')} €</strong></article><article><span>Panier moyen</span><strong>{orders.length ? `${(revenue / orders.length).toFixed(2).replace('.', ',')} €` : '0,00 €'}</strong></article></section><section className="panel finance-report"><div><strong>Clôture et déclaration</strong><span>Journal des ventes, TVA collectée et export comptable</span></div><button className="action-button" onClick={() => window.print()}>Imprimer le rapport</button></section></> }
function SettingsModule({ user, onLogout }: { user: SessionUser | null; onLogout: () => void }) { return <section className="panel settings-module"><div><strong>Session active</strong><span>{user?.name} · {user?.role}</span></div><button className="action-button" onClick={onLogout}>Fermer la session</button></section> }
function LoginScreen({ onLogin }: { onLogin: (user: SessionUser, token: string) => void }) { const [role, setRole] = useState<Role>('manager'); const [pin, setPin] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const submit = async () => { setLoading(true); setError(''); try { const session = await login(role, pin); onLogin(session.user, session.token) } catch { setError('Code incorrect pour ce rôle') } finally { setLoading(false) } }; return <div className="login-screen"><div className="login-card"><div className="brand login-brand"><span className="brand-mark"><Utensils size={18} /></span><span>Service<span className="brand-accent">Pilot</span></span></div><p className="eyebrow">ACCÈS ÉQUIPE</p><h1>Ouvrir une session</h1><p className="login-subtitle">Choisissez votre poste et saisissez votre code.</p><label>Poste<select value={role} onChange={(event) => setRole(event.target.value as Role)}><option value="manager">Gérante</option><option value="server">Serveur</option><option value="kitchen">Cuisine</option><option value="cashier">Caissier</option></select></label><label>Code d’accès<input type="password" inputMode="numeric" value={pin} onChange={(event) => setPin(event.target.value)} onKeyDown={(event) => event.key === 'Enter' && submit()} placeholder="••••" /></label>{error && <p className="login-error">{error}</p>}<button className="primary-button login-submit" disabled={!pin || loading} onClick={submit}>{loading ? 'Connexion...' : 'Ouvrir la session'}</button></div></div> }
function ReservationModal({ onClose, onSubmit }: { onClose: () => void; onSubmit: (data: { name: string; time: string; people: number }) => void }) { const [name, setName] = useState(''); const [time, setTime] = useState('19:30'); const [people, setPeople] = useState(4); return <div className="modal-backdrop" onClick={onClose}><div className="modal" onClick={(event) => event.stopPropagation()}><div className="modal-heading"><div><p className="eyebrow">NOUVEAU RENDEZ-VOUS</p><h2>Ajouter une réservation</h2></div><button onClick={onClose} aria-label="Fermer">×</button></div><label>Nom du client<input value={name} onChange={(event) => setName(event.target.value)} placeholder="Ex. Camille Durand" /></label><div className="modal-fields"><label>Date<input type="date" defaultValue="2026-09-24" /></label><label>Heure<input type="time" value={time} onChange={(event) => setTime(event.target.value)} /></label></div><label>Nombre de personnes<select value={people} onChange={(event) => setPeople(Number(event.target.value))}><option value="2">2 personnes</option><option value="4">4 personnes</option><option value="6">6 personnes</option><option value="8">8 personnes</option></select></label><button className="primary-button modal-submit" disabled={!name.trim()} onClick={() => onSubmit({ name, time, people })}>Créer la réservation <ArrowUpRight size={16} /></button></div></div> }
export default App
